---
kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64

clone:
  disable: true

host_aliases: &host_aliases
  - 'gitea-127.0.0.1.sslip.io:10.96.181.94'

steps:
  - name: clone from local gitea
    image: alpine/git
    commands:
      - git clone http://gitea-127.0.0.1.sslip.io:3000/demo/drone-java-quickstart.git .
      - git checkout $DRONE_COMMIT
    extra_hosts: *host_aliases

  - name: ensure nexus is available
    image: alpine
    pull: if-not-exists
    commands:
      - apk update
      - apk add curl bash
      - if [ "$(curl -s -w '%{http_code}' http://nexus.default:8081/nexus )" = "302" ]; then exit 0; else exit 1; fi
  - name: test-java-application
    image: docker.io/kameshsampath/drone-java-maven-plugin:v1.0.0
    pull: if-not-exists
    settings:
      maven_mirror_url: http://nexus.default:8081/nexus/content/groups/public/
      goals:
        - clean
        - test
      maven_modules:
        - springboot
  - name: build-java-application
    image: docker.io/kameshsampath/drone-java-maven-plugin:v1.0.0
    pull: if-not-exists
    settings:
      maven_mirror_url: http://nexus.default:8081/nexus/content/groups/public/
      goals:
        - clean
        - -DskipTests
        - install
      maven_modules:
        - springboot
trigger:
  branch:
    - main
