---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-build-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drone-build-bot-edit
  namespace: drone
subjects:
- kind: ServiceAccount
  name: drone-build-bot
  namespace: drone
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit 
  apiGroup: rbac.authorization.k8s.io